RESUME_HEADERS = {
    'language':[
        'language', 
        'languages', 
        'languages known', 
        ],
    'objective':[
        'ABOUT',
        'Declaration',
        'Description', 
        'objective', 
        'profile', 
        'career goal',
        'career objective',
        'employment objective',
        'professional objective',        
        'career summary',
        'professional summary',
        'summary of qualifications',
        'summary',
        ],
    'projects':[
        'projects',
        'personal projects',

        ],
    'contact_info':[
        'personal info', 
        'personal profile',
        ],
    'skills':[
        'skills and rating',
        'skills',
        'key skills',
        'credentials',
        'areas of experience',
        'areas of expertise',
        'areas of knowledge',
        'skills',
        "other abilities",
        'career related skills',
        'professional skills',
        'specialized skills',
        'technical skills',
        'computer skills',
        'personal skills',
        'computer knowledge',        
        'technologies',
        'technical experience',
        'proficiencies',
        'language competencies and skills',
        'programming languages',
        'competencies'
        ],
    'work_and_employment':[
        'work experience',
        'career profile',
        'employment history',
        'work history',
        'work experience',
        'experience',
        'professional experience',
        'professional background',
        'additional experience',
        'career related experience',
        'related experience',
        'programming experience',
        'freelance',
        'freelance experience',
        'army experience',
        'military experience',
        'military background'
        ],
    'certificate':[
        'certificates', 
        'certifications',
        'misc',
        'miscllaneous'
        
        ],
    'education_and_training':[
        'education',
        'education history',
        'academic background',
        'academic experience',
        'programs',
        'courses',
        'related courses',
        'education',
        'qualifications',
        'educational background',
        'educational qualifications',
        'educational training',
        'education and training',
        'training',
        'academic training',
        'professional training',
        'course project experience',
        'related course projects',
        'internship experience',
        'internships',
        'apprenticeships',
        'college activities',
        'certifications',
        'special training',
    ],
    'interests':[
        'hobbies', 
        'interests',
        'other skills',
        'inter personal skills',
        'inter-personal skills',
        'interpersonal skills'
        ],
    'awards':[
        'awards',
        'accomplishment',
        'achievement',
        'licenses',
        'presentations',
        'conference presentations',
        'conventions',
        'dissertations',
        'exhibits',
        'papers',
        'publications',
        'professional publications',
        'research',
        'research grants',
        'current research interests',
        'thesis',
        'theses',
        ]
}

# RESUME_HEADERS = {
#     'contact_info':[
#         'contact',
#         'profile'
#     ],
    
#     'objective' :[
#         'career goal',
#         'objective',
#         'career objective',
#         'employment objective',
#         'professional objective',        
#         'career summary',
#         'professional summary',
#         'summary of qualifications',
#         'summary',
#         # 'digital'
#     ],

#     'work_and_employment': [
#         'career profile',
#         'employment history',
#         'work history',
#         'work experience',
#         'experience',
#         'professional experience',
#         'professional background',
#         'additional experience',
#         'career related experience',
#         'related experience',
#         'programming experience',
#         'freelance',
#         'freelance experience',
#         'army experience',
#         'military experience',
#         'military background',
#     ],

#     'education_and_training': [
#         'academic background',
#         'academic experience',
#         'programs',
#         'courses',
#         'related courses',
#         'education',
#         'qualifications',
#         'educational background',
#         'educational qualifications',
#         'educational training',
#         'education and training',
#         'training',
#         'academic training',
#         'professional training',
#         'course project experience',
#         'related course projects',
#         'internship experience',
#         'internships',
#         'apprenticeships',
#         'college activities',
#         'certifications',
#         'special training',
#     ],

#     'skills': [
#         'credentials',
#         'areas of experience',
#         'areas of expertise',
#         'areas of knowledge',
#         'skills',
#         "other skills",
#         "other abilities",
#         'career related skills',
#         'professional skills',
#         'specialized skills',
#         'technical skills',
#         'computer skills',
#         'personal skills',
#         'computer knowledge',        
#         'technologies',
#         'technical experience',
#         'proficiencies',
#         'languages',
#         'language competencies and skills',
#         'programming languages',
#         'competencies'
#     ],

#     'misc': [
#         'activities and honors',
#         'activities',
#         'affiliations',
#         'professional affiliations',
#         'associations',
#         'professional associations',
#         'memberships',
#         'professional memberships',
#         'athletic involvement',
#         'community involvement',
#         'refere',
#         'civic activities',
#         'extra-Curricular activities',
#         'professional activities',
#         'volunteer work',
#         'volunteer experience',
#         'additional information',
#         'interests'
#     ],

#     'accomplishments': [
#         'achievement',
#         'licenses',
#         'presentations',
#         'conference presentations',
#         'conventions',
#         'dissertations',
#         'exhibits',
#         'papers',
#         'publications',
#         'professional publications',
#         'research',
#         'research grants',
#         'project',
#         'research projects',
#         'personal projects',
#         'current research interests',
#         'thesis',
#         'theses',
#     ]
# }